version: '3'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"

  query-service:
    build: ./query-service
    ports:
      - "8000:80"
    depends_on:
      - es

